### ISSUE TITLE
Code Review and Re-Factor Proposal

### ISSUE THREAD

**Issue by rsweetland** [rsweetland/Lean-Charts#1]
Make a plan for what cleanup needs to be done, how to better organize the system, refactoring of classes, methods, etc.

**Comment by phpfour** [comment]
# Lean Charts Refactoring
1. A few base standards:
   - will follow Zend Framework coding standards
   - no short opening tag
   - no singletone
   - no static classes
   - objects methods and properties must have explicit visibility 
   - least amount of coupling 
   - no unnecessary comments
   - no globals
   - no long list of if/else/endif 
   - no support for PHP < 5.1.6
2. Configuration should be stored in .ini file and parsed with a configuration loader class
3. DB related functionality should be separated into DAL classes
4. The helper functions should be encapsulated in an abstract Stat class
5. SonarStatManager.class.php needs to be refactored with clear method naming
6. Framework support should be added as additional class, not in base class (ex: Simplelog_Receiver.class.php)
7. Business logic and presentation code should be separated from each other (ex: SonarStat.class.php)
8. The custom stats should be turned into separate classes, inheriting from the base abstract Stat class
9. Notification of any kind should be separated into different notifier classes (ex: mail function)
10. Need to identify the appropriate entities and object graph
11. Need to have unit tests for majority of the classes 
12. Need to restructure folder paths and file locations to adhere to PEAR distribution standard
13. Can use the twitter's bootstrap framework for presentation - http://twitter.github.com/bootstrap/
14. Need to improve the overall API

**Comment by rsweetland** [comment]
Thanks, Emran. So just to summarize our Skype chat, this is all excellent. The only points we are going to change / not do for now are: 
1. (PEAR directory structure would introduce more complexity than its worth for the time being).
2. Love the idea of using a framework for presentation but would prefer this one: http://www.zurb.com/word/Foundation I'll get password info for access.

I'll make another ticket for the architecture step we talked about. Leaving this one one open for reference.

**Comment by phpfour** [comment]
It's complete as well.
