### ISSUE TITLE
Email Alerts for Volatile Stats

### ISSUE THREAD

**Issue by rsweetland** [rsweetland/Lean-Charts#2]
If a certain log event starts going haywire (ie, too many events / too few events),  an alert should be sent to the SYSTEM_EMAIL with a link to that stat. 

Two methods exist and are documented in SonarStatManager.class.php and need to be wrapped up (and added to a cron script somewhere): alertMax() and alertMin() in lib/SonarStatManager.class.php Other alerts methods will exist in the future..this min / max is a good starting point.

**Comment by phpfour** [comment]
Haven't added this as core functionality, wanted to discuss first. However, added two helper methods called "getMaxValue" and "getMinValue" which can be used to get the max/min value over a period of time. Using these methods, the getValue() method in custom stats can determine if there is any alert situation and can send any kind of notification. Let me know your views on this.

**Comment by rsweetland** [comment]
That seems way better! And way more flexible since people would probably want different alerts for different types of stats...some stats maybe really volatile and not as important and some may have very precise alert conditions (i.e., if response time rises above x). 

Although how would one add an alert to a non-custom graph? (i.e., I want to be alerted if my "Users Logged In) graph goes below 30% of the lowest value in 3 weeks).

**Comment by rsweetland** [comment]
Ok, here are some more specific ideas. This would go in the custom-stats extension

``` php
    public function setAlerts() {
        $this->helper->setAlertIfOver(value, email | sms | both);
        $this->helper->setAlertIfUnder(value, email | sms | both); 
        $this->helper->setAlertIfPresent(email | sms | both); //for example, if there is an error logged in the system 
    }
```

There could, of course be more alerts. 

This is what would be good for starters.

I am wondering if we could apply this to non-custom stats? For example, I want to know if my user logins goes above 50 in one hour. (That's just a simple event, not a custom event). Thoughts?
