### ISSUE TITLE
Application Change-Log / Timeline Plotted Against Line Graphs

### ISSUE THREAD

**Issue by rsweetland** [rsweetland/Lean-Charts#4]
Here is a visual of what this would look like: 

[Graph with Change-Log Events](http://cl.ly/3e341o0g0r0e1I0W0W29)

[ Note that design is not a priority right now. These wireframes were only created to show functionality, not design. So please just use simple markup such as divs, simple elements, etc. Minimal CSS needed (that will be another iteration). ]

As you can see, events are simply plotted against the timeline. The graphing library we use (Highcharts) doesn't support an annotated timeline, however, a workaround has been proposed and it is fairly straight forward (involving overlaying a bar chart on a line chart):

http://highslide.com/forum/viewtopic.php?f=9&t=6751 

For simplicity, every change event will be plotted on every graph – large or small. In the future we may add a system to filter out certain events from a graph.

The other requirement for this feature is a simple form to add these changes (ie, enhancements you make to the application)  Note there is no editing..just adding and deleting:

[Event Log Entry Screen](http://cl.ly/1E13113W210b1P3k1w0o)
[Dashboard of Graphs with Change-Log Events](http://cl.ly/3M1C3V3c3O3Q3w2q3u1h)

--------- Copied from Readme.txt ------------
See wireframe diagram. This consists of a simple form to add change-log events 
(ie, enhancements you make to the application) which are then plotted on the 
line graphs so you can view how changes affected your metrics.

**Comment by phpfour** [comment]
Added as per wireframe.
