### ISSUE TITLE
Helper Function to Count Events Limited By Contents in the "Data" field

### ISSUE THREAD

**Issue by rsweetland** [rsweetland/Lean-Charts#8]
Function to count events where data meets certain conditions.

Example:  
countEventsWhere(eventName, data-conditions-present, $cohort);  
Example:
$numInvites  = countEventsWhere('Invite sent', 'joe@smith.com', $cohort);  (Maybe we make this more abstract by putting into an array, etc so we can search for the number of events where "numValue > 10" or something like that).  Cohort would apply here as well.

**Comment by phpfour** [comment]
Added a new helper on the StatHelper class.
